version: '3'
services:
  exercise:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGHOST=postgres
    volumes:
      - .:/usr/src
      - "/usr/src/node_modules"

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5