version: '3'
services:
  exercise:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
    volumes:
      - .:/usr/src
      - "/usr/src/node_modules"

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
